-   id: check-mkdocs
    name: check-mkdocs
    description: check mkdocs project documentation works correcly
    entry: check-mkdocs
    language: python
    language_version: python3
    pass_filenames: false
